RIOT-OS/riot-os.org

community.html
As reported in #14 the links to the emails are broken. This adds the missing `mailto:`.
Fixes #14
=> community: fix email links

_includes/header.html
This adds the `scrollto` class to the `Social Media` link, so it triggers the correct scrolling function in `main.js`. This prevents from scrolling to the middle of the social images, when clicking from within the community page.
=> includes/header: add missing 'scrollto' class

.github/workflows/pr_preview.yml
This PR adds a GH action to allow a preview deployment to [surge.sh](https://surge.sh/).
This needs a token in the organization secrets that currently is generated via my own account, perhaps we could change this in the future.
Was #13
Depends on #17
=> gh_actions: add Surge PR preview

index.html
With #17 RIOT stats do not contain the amount of contributors, it can be just retrieved from the contributors file. This fixes the counter.
=> index: fix contributors counter

_config_production.yml
this will fix problems with the new site url relaunch.riot-os.org.
=> jekyll: change baseurl to "/"

Makefile, _config_production.yml
This PR adds a missing JEKYLL_ENV variable when running in production. 
This is required to in order to build properly when using PRODUCTION=1.
=> add missing JEKYLL_ENV to production

CNAME
this file is required to enable custom domain names.
note that when configuring a custom domain name using the web frontend, a CNAME file will be automatically created in the `gh-pages` branch. this file will be removed with every automatic deployment based on our GitHub Actions if the CNAME file is not available in master.
=> deployment: add CNAME to allow for custom domain name

CNAME
This PR removes the CNAME file, used by the old Github Pages setup.
Since we are redirecting the traffic internally, we need to get rid of this resolution (otherwise `riot-os.github.io` redirects internally to relaunch.riot-os.org, which already points to the server...)
=> remove CNAME

_includes/use-cases-carousel.html, _layouts/use-case.html, _sass/components/use-cases-carousel.scss
This PR removes the rounding of logos in the use-cases pages, and makes the carousel of equal height by limiting the number of lines in the quotes, as described in #52.
For testing I suggest rebasing on top of #51, which introduces a quote that is smaller than the current ones.
Fixes #52.
=> includes/use_cases_carousel: limit quote lines

index.html
Now that the new HiL nightlies website is up, we should link to it.
=> fix: Update link to HiL nightlies

_layouts/use-case.html
This adds `target="_blank"` to the company link in the use-case layout.
Reported in #26.
=> _layouts/use-case: open company link in _blank

.github/workflows/deployment.yml
This PR adapts the deployment workflow to deploy the website directly to an internal server (HAW).
Since we already had an IPv6 proxy running there (and the fact Github Pages complained regarding asymmetric SSH keys for IPv4 and IPv6), we opted to skip the proxy and simply serve the website from there.
The output of this PR can be seen in https://github.com/jia200x/riot-os.org/actions/runs/710035465. As expected, the files were deployed in the server:
```
-bash$ ls
2021    boards.html    community.html     cpus.html     faqs          index.html       portfolio-details.html
assets  branding.html  contributors.html  drivers.html  imprint.html  inner-page.html  use_cases
```
The GH Secrets were already added to the repository, so we should se the effects right after merge
=> gh/workflows/deployment: adapt to rsync

index.html
This fixes the broken link to Embedded Unit on the index page. Thanks https://twitter.com/goshik/status/1378965521618571266
=> index: fix link to Embedded Unit

_includes/header.html
I often find myself on the RIOT-OS Homepage, when in reality I wanted to go to the docs. While there is a link somewhere on the homepage i takes some time to get there.
this adds a link into the users navigation.
=> Add a link to the documentation in the Header bar

community.html
Just a small nitpick from #89: the alternative text for the image should say 2021 instead of 2020.
=> community: fix RIOT Summit 2021 alt text

README.md
This adds the Github badge for the deployment workflow to the `README.md`, allowing to see the status at a glance.
Edit: To see how it looks check the rich diff of the file https://github.com/RIOT-OS/riot-os.org/pull/94/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
=> README: add deployment workflow badge

Gemfile
There seems to be an issue when serving jekyll on Ruby 3.0. The problem and solution are explained in https://github.com/jekyll/jekyll/issues/8523. This adds `webrick` gem as a dependency. Not sure how this affects other versions, but at least I need it locally to actually be able to bring the server up.
Let's see what the CI says, also maybe some other maintainer can check with their setup?
=> Gemfile: add webrick dependency

_includes/header.html
This PR aims for exposing tutorials by the RIOT community.
During this year's General Assembly we had a discussion that some tutorials (in particular related to connecting to common cloud platforms) to get easily started would be helpful. On Hackster.io there are several tutorials that show how to connect RIOT to AWS etc.
=> add link to Hackster.io under Users in the menu

.github/workflows/deployment.yml
Github disables workflows from repos that have no activity in the last 60 days. This causes our deployment workflow to be disabled. To avoid hitting this limit, we can use the [Keepalive Workflow](https://github.com/marketplace/actions/keepalive-workflow) action to add a commit every 50 days. This PR adds the action as a step of `deployment`, which runs everyday.
=> github/workflows: add keepalive dummy commit step

.github/workflows/deployment.yml
As discussed in #103, the keepalive workflow step is failing due to permissions to push to `master`. Instead of removing all protections for `master`, we now allow admins to push, and added @riot-ci to the group. We then created an access token for @riot-ci, added it to the repo's secrets and now it's being used.
We're not 100% this is the final solution, more settings may need tweaking...
@miri64
=> github/workflows: add token for keepalive

.github/workflows/deployment.yml
The ruby setup action that we use is deprecated. Update to the replacement: https://github.com/ruby/setup-ruby
=> github/deployment: update ruby action

Gemfile.lock
#98 added a new dependency to Gemfile, this updates the .lock, because the GH seems to complain about it.
=> Gemfile.lock: update to latest deps

.github/workflows/deployment.yml
This fixes the Jekyll to a version using a sass-embedded version compatible with the RubyGems in the docker container.
Tested locally using [`act`](https://github.com/nektos/act)
=> github/deployment: Fix Jekyll version

_faqs/faq-03.md, _faqs/faq-07.md
- in FAQ 03, fix broken link to development procedures
- in FAQ 07, use a better link to supported hardware
=> Fix some links in FAQS

.github/workflows/deployment.yml
This didn't work and shows deployment action as failing. Let's remove it...
See #103
=> github/workflows: remove keepalive

index.html
Don't call RIOT a microkernel, that just sets the wrong expectations.
We only have threads, but no separation between them or any notion of kernel/userspace.
By that notion Linux would also be a microkernel.
=> index: microkernel -> small kernel

.github/workflows/deployment.yml
For some time the deployment action [seems to be failing](https://github.com/RIOT-OS/riot-os.org/actions/runs/7381644762/job/20080409643). The error:
```
ERROR:  Error installing bundler:
The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```
This tries applying the suggested solution of setting the bundler version to 2.4.22. Not sure we can test if this fixes the issue without merging...
=> Actions/deployment: specify bundler version

_sass/pages/index.scss, assets/js/main.js, community.html, index.html
As a piggyback I also removed the twitter link from the community page.
=> index.html: use mastodon timeline instead of twitter timeline

_faqs/faq-13.md, _includes/footer.html
Fixes https://github.com/RIOT-OS/riot-os.org/issues/79 and follows the suggestion by @sirocyl.
=> footer: Add link to riot-os.org GitHub repo

community.html
Now that the vision is in the official home of doc, let's update the links.
=> community.html: update vision link

_faqs/faq-02.md, _faqs/faq-12.md, index.html
This makes FAQs linkable, as discussed in https://github.com/RIOT-OS/riot-os.org/pull/125/commits/ef6c8e309bebd793edb00724f457956bb73bb366#r1574781620 (and also piggy-backs a small fixup to make an absolute URL a clickable link).
=> Make FAQs linkable

_sass/_general.scss, _sass/pages/index.scss
One more from my side. I noticed that the formatting of the subsections in faq-12 is a bit off in the output. This fixes the top margin for the headings.
=> sass/general: fix top margin for FAQ subsections

_sass/pages/index.scss
As a follow-up of https://github.com/RIOT-OS/riot-os.org/pull/127#issuecomment-2070474342, this moves the anchors of FAQ entries below the sticky website header. It just adds 9 lines of CSS, so probably worth the effort @miri64 ?
Tested both on mobile and desktop screen (the sticky header size doesn't change).
Can be tested by opening https://riot-os-riot-os-org-preview-129.surge.sh/#faq-1
=> sass/index: move FAQ entry anchors below sticky header

community.html
In #121 I accidentally removed the `#socialmedia` anchor with the twitter card. This re-adds it to the mastodon card.
=> community: re-instate #socialmedia

_faqs/faq-12.md
This fixes a typo, so that the reference in the reference style link and in the reference specification match.
=> _faqs/faq-12.md: Fix broken link

index.html
As @jkarinkl pointed out in #138: There are two broken links wrt the mailing lists.
This PR fixes one link and removes the other one as the mailing list has been deleted a while ago.
=> index.html: fix broken mailing list links

_faqs/faq-02.md
While reviewing #143 I noticed a link to our very old devel mailinglist that leads to a 404. This PR moves the link to the archived thread in the forum.
=> faqs: Update devel archive link to forum

_includes/header.html, community.html, index.html
All of the user documentation now lives under https://guide.riot-os.org.
Progress was tracked under:
- https://github.com/RIOT-OS/RIOT/issues/21575
So I changed the link to the documentation to the guides site, which contains the most useful documentation for beginners.
The API-Documentation (doxygen) is linked there very prominently as well, so it is still easy to discover.
Furthermore some links pointed to outdated user documentation that just shows an empty deprecated page. I updated these to the guide documentation counterparts as well.
=> Replace link to doxygen with link to guides and fix link to deprecated doxygen pages
