community.html
This PR fixes broken links in the community page.
=> community: fix broken links to images

README.md
Just some things I noticed while trying to build the website for the first time as a Ruby/Jekyll noob.
=> README.md: Make README more easier to follow for ruby newcomers

branding.html
This PR fixes broken links in the branding page.
=> branding: fix broken links to logo

index.html
This fixes the links in the landing page to the blog posts, by correctly adding the base URL.
=> index: fix blog links

_layouts/blog.html, _posts/2020-12-31-test.md, index.html
This displays the list of authors (when available) both in the blog entry header and in the index boxes.
Currently an author can define:
- name
- email
- githubid
- affiliation
But this can easily be extended in the future.
=> index/blog: list authors

_layouts/blog.html
This fixes the issues pointed out in https://github.com/RIOT-OS/riot-os.org/pull/21
=> blog: fix author social badges links

_includes/header.html, _sass/components/navbar.scss
This PR modifies the navbar items under the "Community" section:
- adds an icon to indicate external links, so the user is not surprised
- changes the target of these external links to `_blank`
- changes the order to group external and internal links
=> [RFC] includes/header: include external icon and change target

_includes/footer.html, _includes/header.html, _includes/social-media.html, _includes/use-cases-carousel.html, _layouts/blog.html, _layouts/use-case.html, branding.html, community.html, contributors.html, index.html
This PR fixes some accessibility items found by webaccessibility.com.
Check the PR preview and make sure that everything looks like it should.
I will provide a link to the results of webaccessibility.com for this branch as soon as GH Actions deploys the preview
=> accessibility: fix issues pointed out by webaccessibility.com

_includes/use-cases-logo-wall.html
This centers the logos in the logo wall and changes the link target to open them in new tabs.
=> Logo-wall: center logos and open links in new tab

_includes/header.html, _includes/use-cases-carousel.html, _sass/components/use-cases-carousel.scss
This PR changes the ID of the Use Cases Carousel to `use-cases`, which makes a nicer and simpler URL.
=> includes/use-cases-carousel: change anchor to 'use-cases'

_sass/_general.scss, _sass/pages/drivers.scss, assets/css/main.scss, drivers.html
This fixes some missing colors in primary buttons. Also adapts the style of the drivers list to have a similar look to the cpus and boards.
Fixes #64
=> Fix colors and drivers list

index.html
This PR updates the link to boards and adds links to cpu and driver pages, on the index page.
=> index: update links to boards, cpus, drivers

Gemfile.lock
This updates the kramdown gem to a newer version.
=> Gemfile.lock: update kramdown

index.html
An attempt to fix #27, as suggested [here](https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/19) by @maribu.
=> index: reword POSIX compliance

_includes/driver_list.html, _includes/social-media.html, boards.html, branding.html, community.html, contributors.html, cpus.html, drivers.html, index.html
Adds `target=_blank` to all external links. Fixes #26.
I think I got all of them, but please double check.
=> treewide: open external links in _blank

_faqs/faq-06.md
This modifies the FAQ#6 to:
- bring the security contact up and give it more prominence
- replace old mailing list with the new forum email addresses
- open links in new tabs
=> faqs/06: reword and add new email address

community.html
See https://github.com/RIOT-OS/riot-os.org/pull/87#issuecomment-917134403
=> community: Add top-margin to hackster.io icon

index.html
at least you won't find much there
=> There is no such thing as freenode

index.html
Since RIOT release 2022.01, RIOT offers convenient integration of Rust application programming, with wrappers interfacing to RIOT modules such as timers, network stack.
This PR raises awareness for this feature.
=> index: add Rust to feature list and link to Rust RIOT doc

.github/workflows/deployment.yml
Adds remote port option from secrets.
=> github/deployment: add remote port

.github/workflows/deployment.yml
After enabling I would like to trigger...
=> deployment.yml: Add manual trigger

_faqs/faq-10.md
There now is a Raspberry Pi MCU (RP2040) which is supported by RIOT. This brings the doc up in sync with reality.
=> _faqs: Update FAQ question regarding the Raspberry Pi

_faqs/faq-02.md
I found that the link to "this one" explanation of why LGPL did not work anymore.
=> faq-02: Fix url

.github/workflows/deployment.yml
It seems like there is a deployment failure...
I don't really know anything about this stuff but maybe this fixes it.  There was a lot of trial and error.
=> ci: fix ruby and gem version

.github/workflows/deployment.yml, .github/workflows/preview_pr.yml, .github/workflows/receive_pr.yml
This should fix the error in https://github.com/RIOT-OS/riot-os.org/actions/runs/11628564420/job/32383936037
=> gh-actions: bump action versions

_tools/fetch_riot_data.py
I forgot about pagination in the GitHub API. With this fix, Michel, Dylan, Gunar, and Mikolai (all on page 2 of the maintainer team API results) should also now be visible in the maintainer list.
=> fetch_riot_data.py: fetch pages >1 for maintainers
